### ISSUE TITLE
RN apps for tests are not optimized

### ISSUE THREAD

**Issue by RomanSytnyk** [nateshmbhat/flutter-rn-performance-benchmarks#1]
For that test you used Animated package from RN. But almost nobody use it nowadays due to performance.

Fair test should be done with Reanimated3 library, commercial standard for React Native apps.

Also, FastImage is quite outdated lib as well. You can use stock Image, or @expo/image (better solution)

Plus, you can try to measure performance with new architecture enabled (it's disabled in grade settings now).

List test also has not optimized code, without any memoization and etc for renderItem, what can influence performance. 
Also, you can try to measure performance with a FlashList instead of FlatList.

In my opinion, if we do the test, we should use commercial standards for it (at least use Reanimated3 for animations, maybe use Expo and @expo/image, FlashList instead of FlatList as an option, and also make tests with new architecture enabled).

Thanks.
Best regards.

**Comment by nateshmbhat** [comment]
Hey Roman, appreciate your comments. Here's my take on this.
I did test it with Reanimated v3 for list view benchmark and the results are much similar to how it's been using Animated API (There were cases where Re-animated api implementation felt more jankier which was unexpected).  Have updated the code also, Feel free to run the benchmarks yourself. 

We do use reanimated library in our current app, but still we face janks in lower end to medium end devices in certain screens. The same screen performed smoothly in low end phones in flutter. Also when number of animated objects increases on the screen, flutter still retains relatively smooth experience while RN starts to struggle.

For example, one of our use case needs us to show confetti particles on screen. The most popular library [react-native-confetti-cannon](https://www.npmjs.com/package/react-native-confetti-cannon) struggled a lot when we used higher number of practicles and the screen was very janky but flutter's confetti [confetti](https://pub.dev/packages/confetti) library performed smoothly for the same number of particles without any visible jank. 

I also tried the reanimated v3 implementation of confetti library [react-native-reanimated-confetti](https://www.npmjs.com/package/react-native-reanimated-confetti) , which also struggled a lot and the screen was frustratingly more janky for the same number of particles. Would be great if you can suggest a better confetti library if it exists.
Regarding expo library, many react native apps use CLI app instead of expo framework (Not to mention the higher application size that expo adds since its a wrapper around CLI)

Regarding the list test, in flutter list also the implementation is similar to how its done in React Native without rigorous optimization or extra memoization, so it's more like apples to apples comparison.
Having said that, I would love to update this benchmark post with more use cases and with flashlist also and see how it goes in comparison with flutter. Stay tuned :) 

Best regards

**Comment by nateshmbhat** [comment]
I enabled new architecture and tried the same benchmark. it didn't make much difference actually. The results are quite unexpected actually. i was expecting much smoother performance but was disappointed. Will post the results in another post just for new architecture React Native tests. 

Thanks and Regards
